---
- name: Deploy Node.js application
  hosts: task3
  become: yes
  vars:
    nodejs_version: "18.20.4"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Node.js
      shell: curl -sL https://deb.nodesource.com/setup_{{ nodejs_version }} | bash -
      tags: nodejs

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present
      tags: nodejs

    - name: Copy application files
      copy:
        src: /home/nivet/tasks/terraform_ansible/ansible
        dest: /home/ubuntu/task3/ansible

    - name: Install application dependencies
      npm:
        path: /var/www/task3-nodejs-app/
        state: present

    - name: Create systemd service file for Node.js app
      copy:
        dest: /etc/systemd/system/task3-app.service
        content: |
          [Unit]
          Description=Node.js Task3 App

          [Service]
          ExecStart=/usr/bin/node /var/www/task3-nodejs-app/app.js
          Restart=always
          User=nobody
          Group=nobody
          Environment=PATH=/usr/bin:/usr/local/bin
          Environment=NODE_ENV=production
          WorkingDirectory=/var/www/task3-nodejs-app

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Node.js app service
      systemd:
        name: task3-app
        enabled: yes
        state: started

    - name: Configure NGINX to proxy requests to Node.js app
      copy:
        dest: /etc/nginx/sites-available/task3-app
        content: |
          server {
              listen 80;

              server_name _;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Enable NGINX site configuration
      file:
        src: /etc/nginx/sites-available/task1-app
        dest: /etc/nginx/sites-enabled/task1-app
        state: link

    - name: Remove default NGINX site configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
